version: '3.3'
services:
  web:
    container_name: php73
    build: 
      context: ./
      dockerfile: Dockerfile
    image: php:7.3-apache
    container_name: php73
    depends_on: 
      - db
    volumes:
     - ./:/var/www/html/
    ports:
     - 8000:80
  db:
    container_name: mysql8
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
     - ./my-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: yauttouringdb
    ports:
      - 6033:3306
  phpmyadmin:
    depends_on:
     - db
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
     - '8080:80'
    environment:
     PMA_HOST: db
